export PATH=/usr/local/bin:$PATH

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
#export COCOS_CONSOLE_ROOT=/Users/ktakahas/cocos2d-x/cocos2d-x-3.3beta0/tools/cocos2d-console/bin
#export PATH=$COCOS_CONSOLE_ROOT:$PATH

#Android NDK PATH
#ANDROID_NDK=/Users/ktakahas/android_cocos3/ndk
#export PATH=$PATH:${ANDROID_NDK}

#Android SDK PATH
#ANDROID_SDK=/Users/ktakahas/android_cocos3/sdk
#export PATH=$PATH:${ANDROID_SDK}

#export NDK_ROOT="$ANDROID_NDK"

# Add environment variable ANDROID_SDK_ROOT for cocos2d-x
#export ANDROID_SDK_ROOT=/Users/ktakahas/android_cocos3/sdk
#export PATH=$ANDROID_SDK_ROOT:$PATH
#export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

export PYENV_ROOT=${HOME}/.pyenv
if [ -d "${PYENV_ROOT}" ]; then
	export PATH=${PYENV_ROOT}/bin:$PATH
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

test -r ~/.bashrc-utf8 && . ~/.bashrc-utf8
